export const techQuotes = [
  { text: "La mejor forma de predecir el futuro es inventándolo.", author: "Alan Kay" },
  { text: "La innovación distingue a los líderes de los seguidores.", author: "Steve Jobs" },
  { text: "Cualquier tecnología suficientemente avanzada es indistinguible de la magia.", author: "Arthur C. Clarke" },
  { text: "El verdadero progreso es el que pone la tecnología al alcance de todos.", author: "Henry Ford" },
  { text: "No temo a los ordenadores. Lo que temo es a la falta de ellos.", author: "Isaac Asimov" },
  { text: "El software es una gran combinación entre arte e ingeniería.", author: "Bill Gates" },
  { text: "Primero resuelve el problema. Luego, escribe el código.", author: "John Johnson" },
  { text: "La tecnología es solo una herramienta. La gente usa las herramientas para mejorar sus vidas.", author: "Tom Clancy" },
  { text: "La ingeniería es el arte de modelar materiales que no entendemos del todo, en formas que no podemos analizar con precisión.", author: "William A. Wulf" },
  { text: "El hardware es la parte del ordenador que puedes golpear.", author: "Anónimo" },
  { text: "Un buen programador es aquel que siempre mira a ambos lados antes de cruzar una calle de sentido único.", author: "Doug Linder" },
  { text: "Si piensas que la tecnología puede resolver tus problemas de seguridad, entonces no entiendes los problemas y no entiendes la tecnología.", author: "Bruce Schneier" },
  { text: "La web como la imaginé, no la hemos visto todavía. El futuro sigue siendo mucho más grande que el pasado.", author: "Tim Berners-Lee" },
  { text: "La simplicidad es la máxima sofisticación.", author: "Leonardo da Vinci" },
  { text: "Los grandes diseños de software no se construyen; se cultivan.", author: "Fred Brooks" },
  { text: "Medir el progreso del desarrollo de software por líneas de código es como medir el progreso de la construcción de aviones por el peso.", author: "Bill Gates" },
  { text: "Para entender la recursividad, primero debes entender la recursividad.", author: "Anónimo" },
  { text: "La computadora nació para resolver problemas que no existían antes.", author: "Bill Gates" },
  { text: "El diseño no es solo cómo se ve o cómo se siente. El diseño es cómo funciona.", author: "Steve Jobs" },
  { text: "Programar es como escribir un libro... excepto que si te saltas una sola coma en la página 126 el libro entero no tiene sentido.", author: "Anónimo" },
  { text: "Todo el mundo en este país debería aprender a programar un ordenador... porque te enseña a pensar.", author: "Steve Jobs" },
  { text: "No te preocupes si no funciona bien. Si todo lo hiciera, no tendrías trabajo.", author: "Ley de Mosher" },
  { text: "El código es como el humor. Si tienes que explicarlo, es malo.", author: "Cory House" },
  { text: "Hazlo funcionar, hazlo bien, hazlo rápido.", author: "Kent Beck" },
  { text: "La perfección (en el diseño) se logra, no cuando no hay nada más que añadir, sino cuando no hay nada más que quitar.", author: "Antoine de Saint-Exupéry" },
  { text: "Hay 10 tipos de personas en el mundo: los que entienden binario y los que no.", author: "Anónimo" },
  { text: "Siempre codifica como si el tipo que termina manteniendo tu código fuera un psicópata violento que sabe dónde vives.", author: "John Woods" },
  { text: "La tecnología no es nada. Lo importante es que tengas fe en la gente.", author: "Steve Jobs" },
  { text: "El único sistema seguro es aquel que está apagado, encerrado en un bloque de titanio, enterrado en concreto, rodeado de gas venenoso y custodiado por guardias bien pagados.", author: "Gene Spafford" },
  { text: "Controlar la complejidad es la esencia de la programación.", author: "Brian Kernighan" },
  { text: "El futuro pertenece a quienes aprenden más habilidades y las combinan de formas creativas.", author: "Robert Greene" },
  { text: "Las buenas ideas provienen de malas ideas, pero solo si hay suficientes.", author: "Seth Godin" },
  { text: "La ciencia de hoy es la tecnología del mañana.", author: "Edward Teller" },
  { text: "No podemos resolver nuestros problemas con el mismo pensamiento que usamos cuando los creamos.", author: "Albert Einstein" },
  { text: "El genio es 1% inspiración y 99% transpiración.", author: "Thomas Edison" },
  { text: "Una máquina puede hacer el trabajo de 50 hombres ordinarios. Ninguna máquina puede hacer el trabajo de un hombre extraordinario.", author: "Elbert Hubbard" },
  { text: "La mejor forma de aprender es haciendo.", author: "Paul Halmos" },
  { text: "La imaginación es más importante que el conocimiento.", author: "Albert Einstein" },
  { text: "El verdadero signo de la inteligencia no es el conocimiento, sino la imaginación.", author: "Albert Einstein" },
  { text: "La lógica te llevará de A a B. La imaginación te llevará a todas partes.", author: "Albert Einstein" },
  { text: "La función de la educación es enseñar a pensar intensa y críticamente.", author: "Martin Luther King, Jr." },
  { text: "No fallé. Solo encontré 10,000 formas que no funcionan.", author: "Thomas Edison" },
  { text: "Si le hubiera preguntado a la gente qué querían, habrían dicho caballos más rápidos.", author: "Henry Ford" },
  { text: "La innovación es tomar dos cosas que ya existen y unirlas de una forma nueva.", author: "Tom Freston" },
  { text: "Casi todo lo que necesitas saber está en algún lugar, si sabes cómo buscarlo.", author: "Anónimo" },
  { text: "El conocimiento se multiplica cuando se comparte.", author: "Anónimo" },
  { text: "Haz que las cosas sucedan, en lugar de esperar a que sucedan.", author: "Anónimo" },
  { text: "El éxito es ir de fracaso en fracaso sin perder el entusiasmo.", author: "Winston Churchill" },
  { text: "No hay atajos para cualquier lugar que valga la pena ir.", author: "Beverly Sills" },
  { text: "Tu tiempo es limitado, no lo desperdicies viviendo la vida de otro.", author: "Steve Jobs" }
];
